version: 2.1

default_workflow_jobs: &default_workflow_jobs
  - lint
  - lint-shell
  - build-http:
      requires:
        - lint
        - lint-shell
  - build-fpm:
      requires:
        - lint
        - lint-shell
  - build-cli:
      requires:
        - lint
        - lint-shell
  - test-fpm:
      requires:
        - build-http
        - build-fpm
        - build-cli
  - test-cli:
      requires:
        - build-http
        - build-fpm
        - build-cli
  - scan-vulnerability:
      requires:
        - build-http
        - build-fpm
        - build-cli
  - push-http:
      context: dockerhub
      filters:
        branches:
          only: 
            - master
      requires:
        - test-cli
        - test-fpm
        - scan-vulnerability
  - push-fpm:
      context: dockerhub
      filters:
        branches:
          only: 
            - master
      requires:
        - test-cli
        - test-fpm
        - scan-vulnerability
        
  - push-cli:
      context: dockerhub
      filters:
        branches:
          only: 
            - master
      requires:
        - test-cli
        - test-fpm
        - scan-vulnerability

workflows:
  version: 2
  lint-build-test-push:
    jobs: *default_workflow_jobs
  nightly:
    jobs: *default_workflow_jobs
    triggers:
      - schedule:
          cron: "0 3 */2 * *"
          filters:
            branches:
              only:
                - master

commands:
  update_docker_compose:
    description: "Update Docker Compose"
    parameters:
      version:
        type: string
        default: "1.22.0"
    steps:
      - run: sudo curl -L https://github.com/docker/compose/releases/download/<< parameters.version >>/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
      - run: sudo chmod +x /usr/local/bin/docker-compose
  docker_load:
    description: "Load Docker images from file"
    parameters:
      image:
        type: string
    steps:
      - run: docker load -i ./tmp/usabillabv_php-<< parameters.image >>.tar
  docker_load_all:
    description: "Load all available docker images"
    steps:
      - docker_load:
          image: http
      - docker_load:
          image: fpm
      - docker_load:
          image: cli

jobs:
  lint:
    machine: true
    steps:
      - checkout
      - run: make lint
  lint-shell:
    machine: true
    steps:
      - checkout
      - run: make lint-shell
  test-cli:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: ./tmp
      - update_docker_compose:
          version: "1.22.0"
      - docker_load_all
      - run: make ci-test-cli
      - store_test_results:
          path: ./test/test-results/
  test-fpm:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: ./tmp
      - run:
          name: Update Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - docker_load_all
      - run: make ci-test-fpm
      - store_test_results:
          path: ./test/test-results/
  scan-vulnerability:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: ./tmp
      - update_docker_compose:
          version: "1.22.0"
      - run:
          name: Install clair-scanner
          command: |
            sudo curl -L https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64 -o /usr/local/bin/clair-scanner
            sudo chmod +x /usr/local/bin/clair-scanner
      - docker_load_all
      - run: make ci-scan-vulnerability
      - store_artifacts:
          path: ./tmp/clair
  build-http:
    machine: true
    steps:
      - checkout
      - run: make build-http
      - run: cat ./tmp/build-http.tags | xargs -I % docker inspect --format='%={{.Id}}:{{index .ContainerConfig.Env 1}}' %
      - run: docker save usabillabv/php -o ./tmp/usabillabv_php-http.tar
      - persist_to_workspace:
          root: ./tmp
          paths:
            - usabillabv_php-http.tar
            - build-http.tags
  build-fpm:
    machine: true
    steps:
      - checkout
      - run: make build-fpm
      - run: cat ./tmp/build-fpm.tags | xargs -I % docker inspect --format='%={{.Id}}:{{index .ContainerConfig.Env 8}}' %
      - run: docker save usabillabv/php -o ./tmp/usabillabv_php-fpm.tar
      - persist_to_workspace:
          root: ./tmp
          paths:
            - usabillabv_php-fpm.tar
            - build-fpm.tags
  build-cli:
    machine: true
    steps:
      - checkout
      - run: make build-cli
      - run: cat ./tmp/build-cli.tags | xargs -I % docker inspect --format='%={{.Id}}:{{index .ContainerConfig.Env 7}}' %
      - run: docker save usabillabv/php -o ./tmp/usabillabv_php-cli.tar
      - persist_to_workspace:
          root: ./tmp
          paths:
            - usabillabv_php-cli.tar
            - build-cli.tags
  push-http:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: ./tmp
      - docker_load:
          image: http
      - run: make ci-push-http
  push-cli:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: ./tmp
      - docker_load:
          image: cli
      - run: make ci-push-cli
  push-fpm:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: ./tmp
      - docker_load:
          image: fpm
      - run: make ci-push-fpm
